default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5  
  template: template0
  username: postgres
  password: "indijanac999"
  
development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
  username: postgres
  password: <%= ENV['indijanac999'] %>