development:
  adapter: postgresql
  encoding: unicode
  database: todo_development
  pool: 5
  username: postgres
  password: *********

test:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 5
  username: postgres
  password: *********

production:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 5
  username: postgres
  password: *********
