development:
  adapter: postgresql
  encoding: unicode
  database: todo_development
  pool: 5
  username: postgres
  password: indijanac999

test:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 5
  username: postgres
  password: indijanac999

production:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 5
  username: postgres
  password: indijanac999
