
development: &defaults
  adapter: postgresql
  database: todo_development
  username: postgres
  password: ""
  encoding: unicode
  pool: 5
test:
  <<: *defaults
  database: todo_test

production:
  <<: *defaults
  database: todo_production

