# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 982b626a120ec12d02c63c29ff0fa64e0a01e4ff7f0fe162c2f98e1038f54af46b33cd33411c648465a730df085b4f6807b1297c53882f2eda80b564396b8b09

test:
  secret_key_base: 37e3776bf5ca99c070a1b91cb1da7d3b610ad811aae04ec1c68d16969fb5b80c7eb47f366602a25bd4dc9ca065379bc3a4a1d2a5a27c4675166a97270604795a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
